"""
publish_package — turns a routed clip into a brand-aware, publish-ready
package (title, description, hashtags, thumbnail text) using local LLMs.

All text is generated by the local model registry; nothing is sent to a
paid API. The package matches BrandTemplates/publish_package.schema.json.
"""
from __future__ import annotations

import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Optional

from . import model_registry as mr
from . import brand_config as bc


def _next_window(posting: dict) -> str:
    tz = posting.get("timezone", "UTC")
    windows = posting.get("windows", ["12:00"])
    now = datetime.now()
    for _ in range(7):  # look up to a week ahead for the next open window
        for w in windows:
            hh, mm = (w.split(":") + ["0"])[:2]
            cand = now.replace(hour=int(hh), minute=int(mm), second=0, microsecond=0)
            if cand > datetime.now():
                return cand.isoformat()  # naive local; publisher converts to tz
        now += timedelta(days=1)
    return (datetime.now() + timedelta(days=1)).isoformat()


def _gen_title(brand: dict, transcript: str, hook: str) -> tuple[str, str]:
    try:
        sys = (f"You write YouTube titles for the brand '{brand['display_name']}'. "
               f"Rules:\n{brand['title_rules']}\nVoice: {brand['voice']}")
        prompt = (f"Clip hook: {hook}\nTranscript excerpt: {transcript[:800]}\n"
                  f"Return ONLY the title, max 100 characters, no quotes.")
        model = mr.resolve("title_generation")
        title = mr.generate(prompt, task="title_generation", system=sys, max_tokens=60)
        if title:
            return title[:100], model
    except Exception:
        pass
    # Deterministic fallback
    base = (hook or brand.get("theme", "")).strip().split("\n")[0]
    fb = f"{brand['display_name']}: {base}"[:100]
    return fb, "template-fallback"


def _gen_caption(brand: dict, transcript: str, hook: str) -> tuple[str, str]:
    try:
        sys = (f"You write YouTube descriptions for '{brand['display_name']}'. "
               f"Rules:\n{brand['caption_rules']}")
        prompt = (f"Clip hook: {hook}\nTranscript excerpt: {transcript[:800]}\n"
                  f"Write 1-3 sentence description, no hashtags here.")
        model = mr.resolve("caption_generation")
        caption = mr.generate(prompt, task="caption_generation", system=sys, max_tokens=200)
        if caption:
            return caption, model
    except Exception:
        pass
    return f"{hook} {brand.get('caption_rules', '')[:0] or ''}".strip() or f"{hook} Follow {brand['handle']} for more.", "template-fallback"


def _gen_hashtags(brand: dict, transcript: str) -> tuple[list[str], str]:
    kw = brand.get("keywords", [])
    try:
        sys = "You return YouTube hashtags as a JSON array of strings, no other text."
        prompt = (f"Brand keywords: {', '.join(kw)}.\n"
                  f"Transcript: {transcript[:600]}\n"
                  f"Return 3-5 relevant hashtags as a JSON array.")
        model = mr.resolve("hashtag_generation")
        out = mr.generate(prompt, task="hashtag_generation", system=sys, max_tokens=120)
        tags = json.loads(out)
        if isinstance(tags, list):
            tags = [t if t.startswith("#") else f"#{t}" for t in tags]
            return tags[:5], model
    except Exception:
        pass
    return [f"#{k.replace(' ', '')}" for k in kw[:4]], "template-fallback"


def _gen_thumb_text(brand: dict, title: str, hook: str) -> tuple[str, str]:
    try:
        sys = (f"You design YouTube thumbnail text for '{brand['display_name']}'. "
               f"Rules:\n{brand['thumbnail_rules']}")
        prompt = (f"Video title: {title}\nHook: {hook}\n"
                  f"Return ONLY the thumbnail overlay text, max 4 words, no quotes.")
        model = mr.resolve("thumbnail_text")
        text = mr.generate(prompt, task="thumbnail_text", system=sys, max_tokens=40)
        if text:
            return text, model
    except Exception:
        pass
    words = title.split()[:3]
    return " ".join(words), "template-fallback"


def build_package(
    clip: dict,
    candidate: dict,
    route: dict,
    quality_gate: Optional[dict] = None,
) -> dict:
    slug = route["brand"]
    brand = bc.load_brand(slug)
    ch = bc.channel_for_brand(slug)
    transcript = candidate.get("transcript_window") or clip.get("transcript", "") or ""
    hook = clip.get("hook_text") or candidate.get("reason") or ""

    title, m_title = _gen_title(brand, transcript, hook)
    caption, m_caption = _gen_caption(brand, transcript, hook)
    hashtags, m_tags = _gen_hashtags(brand, transcript)
    thumb_text, m_thumb = _gen_thumb_text(brand, title, hook)

    package = {
        "brand": slug,
        "display_name": brand["display_name"],
        "target_channel": route["channel_id"],
        "handle": ch["handle"] if ch else brand.get("handle", ""),
        "title": title,
        "description": caption,
        "hashtags": hashtags,
        "thumbnail_text": thumb_text,
        "thumbnail_prompt": f"{brand['thumbnail_rules']} Text overlay: '{thumb_text}'.",
        "hook_text": hook,
        "publish_time": _next_window(brand.get("posting", {})),
        "source_reference": clip.get("source_reference") or clip.get("campaign_id") or "",
        "clip_file_path": clip.get("storage_key") or clip.get("clip_path") or "",
        "brand_fit_score": route["score"],
        "quality_gate": quality_gate or {"passed": True, "note": "pending QC"},
        "status": "draft",
        "generated_by": "mbm_social.publish_package",
        "models_used": {
            "title": m_title,
            "caption": m_caption,
            "hashtags": m_tags,
            "thumbnail": m_thumb,
            "routing": mr.resolve("channel_selection"),
        },
    }
    return package


def save_package(package: dict, out_dir: Optional[Path] = None) -> Path:
    out_dir = out_dir or (Path(__file__).resolve().parent.parent / "publish_queue")
    out_dir.mkdir(parents=True, exist_ok=True)
    fname = out_dir / f"{package['brand']}_{datetime.now():%Y%m%d_%H%M%S}.json"
    fname.write_text(json.dumps(package, indent=2, ensure_ascii=False), encoding="utf-8")
    return fname
