"""add_missing_campaign_columns

Revision ID: d77bf3fd95ce
Revises: 003_add_social_posts
Create Date: 2026-07-14 18:46:13.497591

"""
from alembic import op
import sqlalchemy as sa


revision = 'd77bf3fd95ce'
down_revision = '003_add_social_posts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('payout_per_1k_views', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('max_payout_cap', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('platform_name', sa.String(length=50), nullable=False, server_default='Clipping.com'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'platform_name')
    op.drop_column('campaigns', 'max_payout_cap')
    op.drop_column('campaigns', 'payout_per_1k_views')
    # ### end Alembic commands ###
